name: bootcamp-gol

volumes:
  redpanda-db: null
  mongo-db: null
  redis-db: null
  pg-db: null

services:
  base-app:
    build: .
    environment:
      - DEV_PLATFORM=DOCKER
      - NODE_ENV=development
    volumes:
      - ../:/app
  # ----------------------------------------------------------------------------
  # CORE MICROSERVICES
  # ----------------------------------------------------------------------------
  api:
    extends: base-app
    command: npx nx run api:serve
    ports:
      - '8080:8080'
      - '9229:9229'
  # ----------------------------------------------------------------------------
  # THIRD-PARTY MICROSERVICES
  # ----------------------------------------------------------------------------
  mongo:
    image: mongo:latest
    volumes:
      - mongo-db:/data/db
    ports:
      - '27017:27017'
    command: --bind_ip_all --noauth
  redis:
    image: redis:latest
    volumes:
      - redis-db:/data
    ports:
      - '6379:6379'
  redpanda:
    image: docker.redpanda.com/vectorized/redpanda:v21.11.15
    ports:
      - '8081:8081'
      - '8082:8082'
      - '9092:9092'
      - '28082:28082'
      - '29092:29092'
    command:
      - redpanda
      - start
      - '--smp'
      - '1'
      - '--reserve-memory'
      - 0M
      - '--overprovisioned'
      - '--node-id'
      - '0'
      - '--kafka-addr'
      - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - '--advertise-kafka-addr'
      - PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
      - '--pandaproxy-addr'
      - PLAINTEXT://0.0.0.0:28082,OUTSIDE://0.0.0.0:8082
      - '--advertise-pandaproxy-addr'
      - PLAINTEXT://redpanda:28082,OUTSIDE://localhost:8082
  redpanda-console:
    image: docker.redpanda.com/redpandadata/console:latest
    ports:
      - '9002:8080'
    environment:
      KAFKA_BROKERS: redpanda:29092
    depends_on:
      - redpanda
